server:
  port: 9002

management:
  port: 9012

spring:
  application:
    name: TurbineServer9002

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7001/eureka/

turbine:
  appConfig: ZUUL3001,RESTAPI,GATEVIEW8001
  aggregator:
    clusterConfig: default
  clusterNameExpression: new String("default")


