server:
    port: 3001

eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:7001/eureka/
spring:
    application:
        name: Zuul3001
zuul:                    
  routes:
    ribbon:
      path: /ribbonClass/**
      serviceId: GateView8001
    feign:
      path: /feignClass/**
 