server:
  port: 6001

spring:
  application:
    name: ZipkinServer6001
  sleuth:
    # 不对本身跟踪
    enabled: false
  application:
    name: microservice-zipkin-stream-server-es
  rabbitmq:
    password: guest
    port: 5672
    host: localhost
    username: guest

zipkin:
  storage:
    elasticsearch:
      cluster: elasticsearch-zipkin-cluster
      max-requests: 64
      index-replicas: 1
      hosts: 127.0.0.1:9300
      index: zipkin
      index-shards: 5
    StorageComponent: elasticsearch
    type: elasticsearch

eureka:
  client:
    serviceUrl:
      defaultZone: http://eurekaserver7001.com:7001/eureka/